language: php

branches:
  only:
    - v1.x

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  - npm
  - composer

env:
  global:
    - DEPLOY_DOCS=false
    - PHPDOC=2

matrix:
  fast_finish: false
  include:
    - php: 7.2
      env: DEPLOY_DOCS=true

  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: 7.4

before_install:
  # Update composer
  - composer self-update

  # Setup Git
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis CI Bot"

  # Setup Composer
  - composer global config minimum-stability dev
  - composer global config prefer-stable true
  - export PATH="$(composer config -g home)/vendor/bin:$PATH"

  # Use Node 16
  - nvm use 16

install:
  - composer install --no-interaction
  - npm install

script:
  - composer build:api
  - npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/phpdoc-vuepress
  project-name: "nelson6e65/phpdoc-vuepress [${TRAVIS_COMMIT_RANGE}]"
  on:
    branch: v1.x
    condition: $DEPLOY_DOCS = true
  verbose: true
